language: php
dist: trusty

php:
    - '7.4'
    - nightly

matrix:
    include:
        - php: '7.4'
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
        - php: nightly
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar
    - mkdir -p build/logs

script:
    - vendor/bin/phpstan --level=max analyse src tests
    - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    - vendor/bin/phpcs --standard=Doctrine src

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
